spring:
  application:
    name: charity

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/charity
    username: postgres
    password: postgres
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8081

